import { Client } from 'https://cdn.jsdelivr.net/npm/@gradio/client/dist/index.min.js';

const SUPABASE_URL='https://afzcohtnljnmucrkgcaz.supabase.co';
const SUPABASE_KEY='sb_publishable_EqF-kTNRsSZWhUE8LWB8DQ_UNkTjImv';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const writeModal=document.querySelector('#writeModal');
if(!writeModal) throw new Error('AI_WRITE_MODAL_MISSING');
const sheet=writeModal.querySelector('.sheet');
sheet.innerHTML=`<h3 style="margin:0 0 10px">AI 写歌</h3>
<input class="field" id="aiTheme" maxlength="300" placeholder="歌曲主题，例如：离开家乡后的第一个夜晚">
<div class="row"><select class="field" id="aiMood"><option>温暖</option><option>伤感</option><option>励志</option><option>浪漫</option><option>自由</option><option>热烈</option></select><select class="field" id="aiStyle"><option>流行</option><option>民谣</option><option>电子</option><option>说唱</option><option>摇滚</option><option>R&B</option><option>国风</option><option>纯音乐氛围</option></select></div>
<div class="row"><select class="field" id="aiLanguage"><option>中文</option><option>English</option></select><select class="field" id="aiVoice"><option>女声</option><option>男声</option><option>男女合唱</option><option>自然人声</option></select></div>
<input class="field" id="aiArtist" maxlength="80" placeholder="创作者名称">
<button class="btn" id="makeLyrics" style="width:100%;margin:4px 0 6px">1. AI 生成歌词</button>
<textarea class="field" id="aiLyrics" rows="5" style="height:126px;min-height:126px;max-height:126px;overflow-y:auto;resize:none" placeholder="AI 歌词会出现在这里，也可以自己修改或直接粘贴原创歌词"></textarea>
<input class="field" id="aiTitle" maxlength="120" placeholder="歌曲名称">
<button class="btn" id="makeSong" style="width:100%;margin:4px 0 6px">2. 生成完整歌曲</button>
<p class="notice" style="margin:5px 0">人声歌曲使用多个独立 ACE-Step / DiffRhythm 节点自动切换；纯音乐才使用 Stability。</p>
<div id="aiStatus" class="status"></div>
<div id="generatedBox" class="hidden" style="margin-top:10px"><audio id="generatedAudio" controls style="width:100%"></audio><div class="row" style="margin-top:8px"><button class="btn alt" id="regenerate">重新生成</button><button class="btn" id="saveGenerated">3. 保存到待审核</button></div></div>
<button class="btn alt" id="aiClose" style="width:100%;margin-top:9px">关闭</button>`;

const $=s=>sheet.querySelector(s);
const status=(text,ok=false)=>{const e=$('#aiStatus');e.textContent=text;e.className='status show'+(ok?' ok':'')};
$('#aiClose').onclick=()=>writeModal.classList.remove('show');
let generatedBlob=null;

async function guestApi(body){const r=await fetch(SUPABASE_URL+'/functions/v1/aimusic-guest-points',{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.message||j.error||'游客身份服务失败');return j}
async function ensureGuest(){let token=localStorage.getItem('aimusic_guest_token')||'';if(token){try{const s=await guestApi({action:'status',token});return {token,...s}}catch{localStorage.removeItem('aimusic_guest_token')}}const j=await guestApi({action:'issue'});token=j.token;localStorage.setItem('aimusic_guest_token',token);return {token,...j}}
async function submitTrack(g,{title,artist,genre,description,storage_path}){const r=await fetch(`${SUPABASE_URL}/functions/v1/aimusic-submit-track`,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({guest_token:g.token,title,artist,genre,description,storage_path})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.message||j.error||'待审核记录保存失败');return j}

$('#makeLyrics').onclick=async()=>{const btn=$('#makeLyrics'),theme=$('#aiTheme').value.trim();if(theme.length<2){status('先写歌曲主题');return}btn.disabled=true;status('AI 正在写完整歌词…');try{const r=await fetch(`${SUPABASE_URL}/functions/v1/aimusic-lyrics`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({theme,mood:$('#aiMood').value,style:$('#aiStyle').value,language:$('#aiLanguage').value,voice:$('#aiVoice').value})});const j=await r.json();if(!r.ok||!j?.ok)throw new Error(j?.message||j?.error||'歌词生成失败');$('#aiLyrics').value=j.lyrics;$('#aiTitle').value=j.title||'';status('歌词已生成 ✓ 下一步就在下方。',true);setTimeout(()=>$('#makeSong').scrollIntoView({behavior:'smooth',block:'center'}),80)}catch(e){status('歌词生成失败：'+(e?.message||'请稍后重试'))}finally{btn.disabled=false}};

function timeout(promise,ms,label){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(label||'通道超时')),ms))])}
function extractAudioUrl(value,depth=0){if(depth>7||value==null)return'';if(typeof value==='string'){if(/^https?:\/\//i.test(value)||/\.(mp3|wav|flac|ogg|m4a)(\?|$)/i.test(value))return value;return''}if(Array.isArray(value)){for(const v of value){const u=extractAudioUrl(v,depth+1);if(u)return u}return''}if(typeof value==='object'){for(const k of ['url','path','audio','file','value','data','output']){if(k in value){const u=extractAudioUrl(value[k],depth+1);if(u)return u}}for(const v of Object.values(value)){const u=extractAudioUrl(v,depth+1);if(u)return u}}return''}
async function blobFromResult(result,label){const url=extractAudioUrl(result?.data??result);if(!url)throw new Error(label+'没有返回音频');const r=await fetch(url);if(!r.ok)throw new Error(label+'音频读取失败');const blob=await r.blob();if(!blob.size)throw new Error(label+'返回空音频');return blob}
function vocalPrompt(style,mood,voice){const lang=$('#aiLanguage').value==='中文'?'Chinese Mandarin':'English';return `${style}, ${mood}, ${voice}, ${lang} vocal song, clear lead vocals, accurate lyric singing, polished studio production, full arrangement`}
function pLabel(p){return String(p?.label||p?.parameter_name||p?.name||'').toLowerCase()}
function pDefault(p){return p?.parameter_default??p?.default??p?.value??null}
function mapAceParam(p,lyrics,style,mood,voice){const l=pLabel(p),caption=vocalPrompt(style,mood,voice);if(l.includes('lyric'))return lyrics;if(l.includes('caption')||l==='prompt'||l.includes('description')||l.includes('tags'))return caption;if(l.includes('vocal language')||l==='language')return $('#aiLanguage').value==='中文'?'zh':'en';if(l.includes('instrumental'))return false;if(l.includes('task type'))return 'text2music';if(l.includes('generation mode'))return 'Custom';if(l.includes('audio duration')||l==='duration'||l.includes('seconds'))return 120;if(l.includes('batch size'))return 1;if(l.includes('inference step')||l.includes('infer step')||l==='steps')return 8;if(l.includes('guidance scale')||l==='guidance')return 7;if(l.includes('random seed'))return true;if(l==='seed'||l.includes('manual seed'))return -1;if(l.includes('audio format'))return 'mp3';if(l.includes('scheduler'))return 'euler';if(l.includes('cfg type'))return 'apg';if(l.includes('omega'))return 10;if(l.includes('guidance interval'))return 0.5;if(l.includes('think'))return false;if(l.includes('rewrite')||l.includes('use format')||l.includes('auto score')||l.includes('auto lrc'))return false;if(l.includes('reference audio')||l.includes('source audio')||l.includes('audio upload')||l.includes('audio input'))return null;return pDefault(p)}

async function generateByOfficialAce(space,label,lyrics,style,mood,voice){status(`正在尝试${label}…`);const work=(async()=>{const app=await Client.connect(space,{events:['data','status']});const info=await app.view_api();const eps=info?.named_endpoints||{};const names=Object.keys(eps);let endpoint=names.find(k=>{const ps=eps[k]?.parameters||[],labs=ps.map(pLabel);return labs.some(x=>x.includes('lyric'))&&(labs.some(x=>x.includes('caption'))||labs.some(x=>x==='prompt')||labs.some(x=>x.includes('description')))});if(!endpoint)endpoint=names.find(k=>/generate|music|predict/i.test(k));if(!endpoint)throw new Error(label+'没有生成端点');const ps=eps[endpoint]?.parameters||[];const payload=ps.map(p=>mapAceParam(p,lyrics,style,mood,voice));const result=await app.predict(endpoint,payload);return blobFromResult(result,label)})();return timeout(work,110000,label+'生成超时')}

async function generateByCommunityAce(lyrics,style,mood,voice){status('官方节点繁忙，正在尝试第三个人声节点…');const work=(async()=>{const app=await Client.connect('timefractal/ACE-Step-Turbo-Music-Gen',{events:['data','status']});const info=await app.view_api();const names=Object.keys(info?.named_endpoints||{});let endpoint=names.find(k=>{const p=info.named_endpoints[k]?.parameters||[],labels=p.map(x=>String(x.label||'').toLowerCase());return labels.some(x=>x.includes('lyrics'))&&labels.some(x=>x.includes('prompt')||x.includes('description'))})||names.find(k=>/generate/i.test(k))||names[0]||'/predict';const seed=Math.floor(Math.random()*2147483646)+1;let result;try{result=await app.predict(endpoint,[vocalPrompt(style,mood,voice),lyrics,60,seed,8])}catch(e){if(endpoint!=='/predict')result=await app.predict('/predict',[vocalPrompt(style,mood,voice),lyrics,60,seed,8]);else throw e}return blobFromResult(result,'第三个人声节点')})();return timeout(work,115000,'第三个人声节点生成超时')}

async function generateByAceSimple(lyrics,style,mood,voice){status('前三个节点不可用，正在尝试第四个人声节点…');const work=(async()=>{const app=await Client.connect('ACloudCenter/ACE-Music-Generator',{events:['data','status']});const result=await app.predict('/generate',[120,vocalPrompt(style,mood,voice),lyrics,60,15]);return blobFromResult(result,'第四个人声节点')})();return timeout(work,120000,'第四个人声节点生成超时')}

async function generateByDiffRhythm(lyrics,style,mood,voice){status('前四个节点不可用，正在尝试最后一个人声节点…');const work=(async()=>{const app=await Client.connect('ASLP-lab/DiffRhythm2',{events:['data','status']});const info=await app.view_api();let endpoint=Object.keys(info?.named_endpoints||{}).find(k=>{const p=info.named_endpoints[k]?.parameters||[];return p.some(x=>String(x.label||'').toLowerCase().includes('lyrics'))})||Object.keys(info?.named_endpoints||{})[0];if(!endpoint)endpoint='/predict';const payload=[lyrics,'text',null,vocalPrompt(style,mood,voice),0,true,16,1.3,'mp3','euler'];const result=await app.predict(endpoint,payload);return blobFromResult(result,'DiffRhythm')})();return timeout(work,120000,'DiffRhythm 人声生成超时')}

async function generateByStability(style,mood){const g=await ensureGuest();status('正在使用 Stability 纯音乐通道生成…');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),100000);try{const r=await fetch(`${SUPABASE_URL}/functions/v1/aimusic-generate-audio`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify({guest_token:g.token,lyrics:'',theme:$('#aiTheme').value.trim(),style,mood,voice:'instrumental',duration:180}),signal:ctrl.signal});if(!r.ok){let msg='Stability 不可用';try{const j=await r.json();msg=j?.message||j?.error||msg}catch{}throw new Error(msg)}const blob=await r.blob();if(!blob.size)throw new Error('Stability 返回空音频');return blob}finally{clearTimeout(timer)}}

async function makeFullSong(){const lyrics=$('#aiLyrics').value.trim(),style=$('#aiStyle').value,mood=$('#aiMood').value,voice=$('#aiVoice').value,isInstrumental=style==='纯音乐氛围';if(!isInstrumental&&lyrics.length<40){status('请先生成或填写完整歌词');return}const btn=$('#makeSong');btn.disabled=true;$('#generatedBox').classList.add('hidden');generatedBlob=null;const errors=[];try{if(isInstrumental){generatedBlob=await generateByStability(style,mood)}else{const providers=[()=>generateByOfficialAce('ACE-Step/Ace-Step-v1.5','ACE-Step 1.5 官方人声节点',lyrics,style,mood,voice),()=>generateByOfficialAce('ACE-Step/ACE-Step','ACE-Step 官方人声节点',lyrics,style,mood,voice),()=>generateByCommunityAce(lyrics,style,mood,voice),()=>generateByAceSimple(lyrics,style,mood,voice),()=>generateByDiffRhythm(lyrics,style,mood,voice)];for(let n=0;n<providers.length&&!generatedBlob;n++){try{generatedBlob=await providers[n]()}catch(e){const m=e?.message||String(e);errors.push(m);console.warn('provider failed',n+1,m);status(/zerogpu|quota|limit/i.test(m)?`第 ${n+1} 个人声节点额度已满，自动切换下一个…`:`第 ${n+1} 个人声节点失败，自动切换下一个…`)}}if(!generatedBlob)throw new Error(errors[errors.length-1]||'所有人声节点不可用')}const local=URL.createObjectURL(generatedBlob);$('#generatedAudio').src=local;$('#generatedBox').classList.remove('hidden');status(isInstrumental?'纯音乐生成成功 ✓ 请先试听。':'人声完整歌曲生成成功 ✓ 请先试听。',true);setTimeout(()=>$('#generatedBox').scrollIntoView({behavior:'smooth',block:'center'}),80)}catch(e){console.error(e);status('当前所有歌曲生成节点暂时不可用：'+(e?.message||'请稍后重试'))}finally{btn.disabled=false}}
$('#makeSong').onclick=makeFullSong;$('#regenerate').onclick=makeFullSong;

$('#saveGenerated').onclick=async()=>{const btn=$('#saveGenerated'),title=$('#aiTitle').value.trim(),artist=$('#aiArtist').value.trim();if(!generatedBlob){status('请先生成完整歌曲');return}if(!title||!artist){status('请填写歌曲名称和创作者名称');return}btn.disabled=true;status('正在保存歌曲到云端待审核…');const path=`ai/${Date.now()}-${crypto.randomUUID()}.mp3`;try{const g=await ensureGuest();const up=await db.storage.from('aimusic-audio').upload(path,generatedBlob,{cacheControl:'3600',upsert:false,contentType:generatedBlob.type||'audio/mpeg'});if(up.error)throw up.error;let meta;try{meta=await submitTrack(g,{title,artist,genre:$('#aiStyle').value,description:`AI原创 · ${$('#aiMood').value} · ${$('#aiVoice').value}`,storage_path:path})}catch(e){await db.storage.from('aimusic-audio').remove([path]);throw e}if(typeof window.AIMUSIC_GUEST_AWARD==='function')await window.AIMUSIC_GUEST_AWARD('upload',meta.id);status('保存成功 ✓ 后台待审核已登记。',true)}catch(e){console.error(e);status('保存失败：'+(e?.message||'请稍后重试'))}finally{btn.disabled=false}};

const ordinarySubmit=document.querySelector('#submit');
if(ordinarySubmit)ordinarySubmit.onclick=async()=>{const f=document.querySelector('#file')?.files?.[0],title=document.querySelector('#title')?.value.trim(),artist=document.querySelector('#artist')?.value.trim(),genre=document.querySelector('#genre')?.value||'其他',description=document.querySelector('#description')?.value.trim()||'',box=document.querySelector('#uploadStatus');const msg=(t,ok=false)=>{if(box){box.textContent=t;box.className='status show'+(ok?' ok':'')}};if(!f||!title||!artist){msg('请填写歌名、创作者并选择音频文件');return}if(f.size>15*1024*1024){msg('文件超过 15MB');return}ordinarySubmit.disabled=true;msg('正在上传并登记待审核…');let path='';try{const g=await ensureGuest(),ext=(f.name.split('.').pop()||'audio').toLowerCase().replace(/[^a-z0-9]/g,'');path=`submissions/${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await db.storage.from('aimusic-audio').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type||undefined});if(up.error)throw up.error;let meta;try{meta=await submitTrack(g,{title,artist,genre,description,storage_path:path})}catch(e){await db.storage.from('aimusic-audio').remove([path]);throw e}if(typeof window.AIMUSIC_GUEST_AWARD==='function')await window.AIMUSIC_GUEST_AWARD('upload',meta.id);msg('提交成功 ✓ 已进入后台待审核。',true);document.querySelector('#file').value=''}catch(e){msg('上传失败：'+(e?.message||'请稍后重试'))}finally{ordinarySubmit.disabled=false}};

const pointsBtn=document.querySelector('#pointsBtn'),pointsModal=document.querySelector('#pointsModal'),guestCode=document.querySelector('#guestCode');
if(guestCode)guestCode.textContent='游客积分会自动保存在当前设备。注册正式账号后可合并兑换。';
if(pointsBtn)pointsBtn.onclick=()=>{if(guestCode)guestCode.textContent='游客积分会自动保存在当前设备。注册正式账号后可合并兑换。';pointsModal?.classList.add('show')};
if(new URLSearchParams(location.search).has('g'))history.replaceState(null,'',location.pathname);
