const E=id=>document.getElementById(id);let scenes=[],sceneImages=[],audioBuffer=null,audioBlob=null;
function log(m){const t=new Date().toLocaleTimeString();E('logs').textContent+='\n['+t+'] '+m;E('logs').scrollTop=E('logs').scrollHeight}
function setStatus(m,p){E('status').textContent=m;if(typeof p==='number')E('bar').style.width=Math.max(0,Math.min(100,p))+'%';log(m)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nScenes(sec){if(sec<=30)return 6;if(sec<=60)return 10;if(sec<=180)return 18;if(sec<=300)return 24;return 36}
function localPlan(topic,n){const bits=topic.split(/[。！？!?\n]+/).map(x=>x.trim()).filter(Boolean);const moves=['建立环境与人物','进入主要动作','展示细节特写','推动故事发展','加入自然互动','镜头转换','展示核心亮点','自然收束'];return Array.from({length:n},(_,i)=>{const b=bits[i%Math.max(1,bits.length)]||topic;return{title:'场景 '+(i+1),narration:b+(i===n-1?'，最后自然收束画面。':'。'),prompt:b+'，'+moves[i%moves.length]+'，'+E('style').value+'，高质量，真实自然，电影构图，无文字'}})}
function parsePlan(text,n,topic){try{let x=text.trim();const j=JSON.parse(x),a=Array.isArray(j)?j:(j.scenes||[]);if(a.length)return a.slice(0,n).map((v,i)=>({title:v.title||('场景 '+(i+1)),narration:v.narration||v.voiceover||topic,prompt:v.prompt||v.visual||topic}))}catch(e){}return null}
async function planScenes(){const topic=E('topic').value.trim();if(!topic){alert('先输入主题或文案');return}const n=nScenes(+E('duration').value);setStatus('正在生成脚本和分镜…',8);let p=null;try{const q='请为下面主题制作'+n+'个视频分镜。每个分镜包含 title、narration、prompt。narration 是自然旁白，prompt 是画面描述，风格为'+E('style').value+'。只返回JSON数组，不要任何其他内容。主题：'+topic;const r=await fetch('https://text.pollinations.ai/'+encodeURIComponent(q)+'?model=openai-fast&seed='+(Date.now()%100000),{cache:'no-store'});if(!r.ok)throw Error('text '+r.status);p=parsePlan(await r.text(),n,topic);if(p)log('免费文本模型分镜成功')}catch(e){log('在线分镜失败，改用本地分镜：'+e.message)}scenes=p||localPlan(topic,n);sceneImages=new Array(scenes.length).fill(null);audioBuffer=null;audioBlob=null;drawSceneCards();E('imageBtn').disabled=false;E('voiceBtn').disabled=false;E('renderBtn').disabled=false;setStatus('分镜完成：'+scenes.length+' 个场景',20)}
function drawSceneCards(){E('scenes').innerHTML=scenes.map((s,i)=>'<div class="scene"><img id="img'+i+'"><div><b>'+esc(s.title)+'</b><p>'+esc(s.narration)+'</p></div></div>').join('');sceneImages.forEach((u,i)=>{if(u)E('img'+i).src=u})}
async function fetchSceneImage(prompt,i){let w=1280,h=720;if(E('ratio').value==='9:16'){w=720;h=1280}else if(E('ratio').value==='1:1'){w=1024;h=1024}const u='https://image.pollinations.ai/prompt/'+encodeURIComponent(prompt)+'?model=flux&width='+w+'&height='+h+'&seed='+(1001+i*97)+'&nologo=false';const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('image '+r.status);return URL.createObjectURL(await r.blob())}
async function generateImages(){if(!scenes.length)await planScenes();setStatus('正在生成画面…',25);for(let i=0;i<scenes.length;i++){try{sceneImages[i]=await fetchSceneImage(scenes[i].prompt,i);E('img'+i).src=sceneImages[i]}catch(e){log('场景 '+(i+1)+' 画面失败，导出时用动态背景')}setStatus('生成画面 '+(i+1)+' / '+scenes.length,25+35*(i+1)/scenes.length);await new Promise(r=>setTimeout(r,300))}setStatus('画面阶段完成',60)}
function splitText(text,max){const parts=text.split(/[。！？.!?]/).filter(Boolean),out=[];let cur='';for(const s0 of parts){const s=s0+'。';if((cur+s).length>max&&cur){out.push(cur);cur=s}else cur+=s}if(cur)out.push(cur);return out}
async function getVoiceIndex(){try{const r=await fetch('https://ahm7xmakki.com/api/voices'),j=await r.json();const v=(j.voices||[]).find(x=>/Chinese|Mandarin|China|Taiwan|Xiaoxiao|Yunxi|Xiaoyi/i.test([x.language,x.country,x.name,x.id].join(' ')))||(j.voices||[])[0];if(v){log('配音：'+v.name+' #'+v.index);return v.index}}catch(e){log('读取声音失败：'+e.message)}return 1}
async function generateVoice(){if(!E('narration').checked){audioBuffer=null;audioBlob=null;setStatus('已关闭配音',72);return}if(!scenes.length)await planScenes();setStatus('正在生成中文配音…',62);try{const vi=await getVoiceIndex(),chunks=splitText(scenes.map(x=>x.narration).join(' '),1800),blobs=[];for(let i=0;i<chunks.length;i++){const r=await fetch('https://ahm7xmakki.com/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voiceIndex:vi,text:chunks[i],pitch:0,rate:0})});if(!r.ok)throw Error('tts '+r.status);blobs.push(await r.blob());setStatus('配音 '+(i+1)+' / '+chunks.length,62+10*(i+1)/chunks.length)}audioBlob=new Blob(blobs,{type:'audio/mpeg'});const ac=new (window.AudioContext||window.webkitAudioContext)();audioBuffer=await ac.decodeAudioData(await audioBlob.arrayBuffer());await ac.close();setStatus('配音完成 · '+audioBuffer.duration.toFixed(1)+' 秒',72)}catch(e){audioBuffer=null;audioBlob=null;log('配音失败：'+e.message);setStatus('配音失败，继续生成无旁白版',72)}}