const E=id=>document.getElementById(id);let scenes=[],sceneImages=[],audioBuffer=null;
function log(m){const t=new Date().toLocaleTimeString();E('logs').textContent+='\n['+t+'] '+m;E('logs').scrollTop=E('logs').scrollHeight}
function setStatus(m,p){E('status').textContent=m;if(typeof p==='number')E('bar').style.width=Math.max(0,Math.min(100,p))+'%';log(m)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nScenes(sec){if(sec<=30)return 3;if(sec<=60)return 4;if(sec<=180)return 6;if(sec<=300)return 8;return 12}
function localPlan(topic,n){const bits=topic.split(/[。！？!?\n]+/).map(x=>x.trim()).filter(Boolean);const moves=['建立环境和人物','进入主要动作','展示细节特写','推动故事发展','自然互动','镜头转换','展示核心亮点','自然收束'];return Array.from({length:n},(_,i)=>{const b=bits[i%Math.max(1,bits.length)]||topic;const ending=i===n-1?'，最后自然收束并结束。':'。';return{title:'场景 '+(i+1),narration:b+ending,prompt:b+'，'+moves[i%moves.length]+'，'+E('style').value+'，真实自然，高质量摄影，电影构图，无文字，无水印'}})}
async function planScenes(){const topic=E('topic').value.trim();if(!topic){alert('先输入主题或文案');throw Error('未输入主题')}const n=nScenes(+E('duration').value);setStatus('正在生成分镜…',8);scenes=localPlan(topic,n);sceneImages=new Array(n).fill(null);audioBuffer=null;drawSceneCards();E('imageBtn').disabled=false;E('voiceBtn').disabled=false;E('renderBtn').disabled=false;setStatus('分镜完成：'+n+' 个场景',20)}
function drawSceneCards(){E('scenes').innerHTML=scenes.map((s,i)=>'<div class="scene"><img id="img'+i+'"><div><b>'+esc(s.title)+'</b><p>'+esc(s.narration)+'</p></div></div>').join('');sceneImages.forEach((u,i)=>{if(u)E('img'+i).src=u})}
function dims(){const r=E('ratio').value;if(r==='9:16')return[320,576];if(r==='1:1')return[512,512];return[576,320]}
async function startImage(prompt){const d=dims();const u='/api/image-start?prompt='+encodeURIComponent(prompt)+'&w='+d[0]+'&h='+d[1];const r=await fetch(u,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.id)throw Error(j.message||j.error||('start '+r.status));return j.id}
async function waitImage(id,idx){const began=Date.now();while(Date.now()-began<600000){const r=await fetch('/api/image-status?id='+encodeURIComponent(id),{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.message||j.error||('status '+r.status));if(j.done){if(!j.image)throw Error('没有返回图片');return j.image}const q=j.queue_position!=null?'，队列 '+j.queue_position:'';setStatus('画面 '+(idx+1)+' 正在免费队列'+q,25+30*idx/scenes.length);await new Promise(x=>setTimeout(x,3000))}throw Error('免费队列等待超时')}
async function generateImages(){if(!scenes.length)await planScenes();setStatus('正在提交全部免费画面任务…',25);const ids=await Promise.all(scenes.map(async(s,i)=>{if(sceneImages[i])return null;try{return await startImage(s.prompt)}catch(e){log('场景 '+(i+1)+' 提交失败：'+e.message);return null}}));let done=sceneImages.filter(Boolean).length;await Promise.all(ids.map(async(id,i)=>{if(!id)return;try{sceneImages[i]=await waitImage(id,i);E('img'+i).src=sceneImages[i];log('场景 '+(i+1)+' 画面完成')}catch(e){log('场景 '+(i+1)+' 失败：'+e.message)}done++;setStatus('画面完成 '+done+' / '+scenes.length,25+35*done/scenes.length)}));setStatus('画面阶段完成',60)}
function splitText(text,max){const parts=text.split(/(?<=[。！？.!?])/).filter(Boolean),out=[];let cur='';for(const s of parts){if((cur+s).length>max&&cur){out.push(cur);cur=s}else cur+=s}if(cur)out.push(cur);return out}
function joinBuffers(ac,arr){if(!arr.length)return null;const rate=arr[0].sampleRate,ch=Math.max(...arr.map(b=>b.numberOfChannels)),len=arr.reduce((a,b)=>a+b.length,0);const out=ac.createBuffer(ch,len,rate);let off=0;for(const b of arr){for(let c=0;c<ch;c++){const src=b.getChannelData(Math.min(c,b.numberOfChannels-1));out.getChannelData(c).set(src,off)}off+=b.length}return out}
async function generateVoice(){if(!E('narration').checked){audioBuffer=null;setStatus('已关闭配音',72);return}if(!scenes.length)await planScenes();setStatus('正在生成中文配音…',62);try{const text=scenes.map(x=>x.narration).join(' '),parts=splitText(text,160),AC=window.AudioContext||window.webkitAudioContext,ac=new AC(),bufs=[];for(let i=0;i<parts.length;i++){const r=await fetch('/api/tts?text='+encodeURIComponent(parts[i]),{cache:'no-store'});if(!r.ok)throw Error('TTS '+r.status+' '+await r.text());bufs.push(await ac.decodeAudioData(await r.arrayBuffer()));setStatus('配音 '+(i+1)+' / '+parts.length,62+10*(i+1)/parts.length);if(i<parts.length-1)await new Promise(x=>setTimeout(x,800))}audioBuffer=joinBuffers(ac,bufs);await ac.close();setStatus('配音完成 · '+audioBuffer.duration.toFixed(1)+' 秒',72)}catch(e){audioBuffer=null;log('配音失败：'+e.message);setStatus('配音暂时失败，可继续生成无旁白版',72)}}
